【问题】
vim所設置如果是最原始的vi，那麼是不支持下面一些配置的:
set autochdir      —    E518: Unknown option: autochdir
【解决】
執行yum install vim後，給vim設置別名vi
$ alias vi='vim'
$ which vi
/bin/vi
alias vi='vim'
alias vi='vim'
/usr/bin/vim

在~/.vimrc输入：
set tags=tags;
set autochdir


set nocompatible
set lines=31
set columns=202
set mouse=a "enable mouse
syntax on
filetyp on
filetype plugin indent on
autocmd BufNewFile * normal 12G
set expandtab "Converting tabs to spaces
set tabstop=2
set shiftwidth=2
set autoindent
set cindent
set cino=g0
set nu
